fitur1/urls.py
from django.conf.urls import url
from .views import request_token, index, request_auth, auth_logout
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^authenticate/', request_auth, name='authenticate'),
    url(r'^request-token/', request_token , name='get_token'),
    url(r'^logout/', auth_logout , name='logout'),
]

fitur4/urls.py
from django.conf.urls import url
from .views import add_comment, get_comment
#url for app


urlpatterns = [
    url(r'^add_comment/$', add_comment, name='add_comment'),
    url(r'^get_comment/$', get_comment, name='get_comment'),
]

tp2_uyay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import fitur1.urls as fitur1
import fitur2.urls as fitur2
import fitur3.urls as forum
import fitur4.urls as fitur4

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(fitur1, namespace='login')),
    url(r'^$', RedirectView.as_view(url='login/', permanent = True), name = '$'),
    url(r'^profile/', include(fitur2, namespace='fitur2')),
    url(r'^forum/', include(forum, namespace='forum')),
    url(r'^fitur4/', include(fitur4, namespace='fitur4')),
]

fitur1/models.py
from django.db import models

# Create your models here.
class Company(models.Model):
    companyName = models.CharField(max_length=140)
    companyID = models.CharField(max_length=140)
    companyType = models.CharField(max_length=140)
    companyWeb = models.CharField(max_length=140)
    companySpecialty = models.CharField(max_length=140)
    companyImage = models.CharField(max_length=500)
    companyDescription = models.CharField(max_length=500)
    created_on = models.DateTimeField(auto_now_add=True)

fitur1/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, JsonResponse, HttpResponseRedirect
from django.urls import reverse
from fitur3.models import Forum, Comment
from fitur1.models import Company
from fitur3.forms import ForumForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from fitur2.views import get_company_id
from helper.utils import *
import requests, json

CLIENT_ID = "866hc1so0n9js9"
CLIENT_SECRET = "IFSny4QeaB0XYT8D"
REDIRECT_URI = "http://127.0.0.1:8000/login/request-token/"

# Create your views here.
response = {}
def index(request):
    forum_list = Forum.objects.all()
    paginator = Paginator(forum_list, 3)

    page = request.GET.get('page')
    try:
        forum = paginator.page(page)
    except:
        forum = paginator.page(1)

    response['forum'] = forum
    if 'session-id' in request.session:
        response['flag'] = True;
        data_profile = get_profile_data(request)
        print(data_profile)
        response['nama'] = (data_profile['firstName'] if 'firstName' in data_profile else "") + " " + (data_profile["lastName"] if 'lastName' in data_profile else "")
    else:
        response['flag'] = False;
    return render(request, 'test.html', response)

fitur1/templates/test.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
Profile Perusahaan
{% endblock %}

{% block css %}
<!-- <script type="text/javascript" src="//platform.linkedin.com/in.js">
	api_key:   866hc1so0n9js9
	onLoad:    onLinkedInLoad
	authorize: true
</script> -->
<link rel="stylesheet" type="text/css" href="{% static 'css/fitur1.css' %}" />
<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" /> -->
{% endblock %}

{% block header %}
{% include "partials/header.html" %}
{% endblock %}

{% block content %}

<!-- Print errors if any -->
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
	<strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
	<strong>{{ error|escape }}</strong>
</div>

{% endfor %}
{% endif %}
	<!-- Banner -->
	<section id="banner" style="background-image: url(https://images.unsplash.com/photo-1449024540548-94f5d5a59230?auto=format&fit=crop&w=1189&q=80&ixid=dW5zcGxhc2guY29tOzs7Ozs%3D)">
	<div class="inner">
		<header>
			<h1>Looking for a job?</h1>
			<p>Welcome to TP2-Uyay</p>
		</header>
		<a href="#main" class="button big scrolly">See Job Listings</a>
		<div class="login-logout">
			{% if flag %}
			<a href="{% url 'login:logout' %}" class="btn btn-danger">Logout</a>
			<p style="color: rgba(255,255,255,.5); font-size: medium;">Logged in as {{nama}}</p>
			{% else %}
			<a href="{% url 'login:authenticate' %}" class="button big scrolly" style="background-color: purple">Company Login</a>
			{% endif %}
		</div>
	</div>
	</section>

	<!-- Main -->
	<div id="main">
		<!-- Section -->
		<section class="wrapper style1">
			<div class="inner">
				<header class="align-center">
					<h2>Current Job Listings</h2>
					<p>Find your dream job right here with our trusted companies.</p>
				</header>
				<div class="flex flex-3">
					{% for i in forum %}
					<div class="col align-center">
						<div class="image round fit">
							<img src="{{ i.company.companyImage }}" alt="" />
						</div>
						<h3>{{ i.company.companyName }}</h3>
						<sub>{{ i.date }}</sub>
						<p>{{ i.content }}</p>
						<div id="reply-{{i.id}}" hidden>
							<ul id="reply-list-{{i.id}}" class="list-group list-group-flush"></ul>
							<form class="card-block" action="{% url 'fitur4:add_comment' %}" method="POST">
								{% csrf_token %}
								<h7 class="card-subtitle">Name</h7>
								<input id="name" class="form-control" type="" name="name" title="name">
								<h7 class="card-subtitle">Content</h7>
								<textarea id="content" class="form-control" name="content" cols="30" rows="5" title="content"></textarea>
								<input id="id" name="id" title="id" value="{{i.id}}" hidden>
						<a id="submit-comment-{{ i.id }}" href="javascript:sendReply({{ i.id }})" class="button">Submit</a>
							</form>
						</div>
						<a id="btn-show-comment-{{ i.id }}" href="javascript:showReplies({{ i.id }},false)" class="button">Show replies</a>
					</div>
					{% endfor %}
				</div>

			</div>
		</section>
	</div>

	<nav>
		{% if forum.has_other_pages %}
		<ul class="pagination" style="justify-content: center; margin-top: 20px">
			{% if forum.has_previous %}
			<li class="page-item"><a class="page-link" href="?page={{ forum.previous_page_number }}#main">&laquo;</a></li>
			{% else %}
			<li class="page-item disabled"><span class="page-link">&laquo;</span></li>
			{% endif %}
			{% for i in forum.paginator.page_range %}
			{% if forum.number == i %}
			<li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
			{% else %}
			<li class="page-item"><a class="page-link" href="?page={{ i }}#main">{{ i }}</a></li>
			{% endif %}
			{% endfor %}
			{% if forum.has_next %}
			<li class="page-item"><a class="page-link" href="?page={{ forum.next_page_number }}#main">&raquo;</a></li>
			{% else %}
			<li class="page-item disabled"><span class="page-link">&raquo;</span></li>
			{% endif %}
		</ul>
		{% endif %}
	</nav>

	{% endblock %}

	{% block javascript %}
	<script src="{% static 'js/fitur1.js' %}"></script>
	<script src="{% static 'js/comment.js' %}"></script>
	{% endblock %}