fitur1/urls.py
from django.conf.urls import url
from .views import request_token, index, request_auth, auth_logout
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^authenticate/', request_auth, name='authenticate'),
    url(r'^request-token/', request_token , name='get_token'),
    url(r'^logout/', auth_logout , name='logout'),
]

fitur2/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', show_profile, name='showProfile'),
    url(r'^id/$', get_company_data, name='get_company_id'),
]

tp2_uyay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import fitur1.urls as fitur1
import fitur2.urls as fitur2
import fitur3.urls as forum
import fitur4.urls as fitur4

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(fitur1, namespace='login')),
    url(r'^$', RedirectView.as_view(url='login/', permanent = True), name = '$'),
    url(r'^profile/', include(fitur2, namespace='fitur2')),
    url(r'^forum/', include(forum, namespace='forum')),
    url(r'^fitur4/', include(fitur4, namespace='fitur4')),
]

fitur2/models.py
from django.db import models

# Create your models here.

fitur2/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import requests, json

# Create your views here.
response = {}


def show_profile(request):
    print('session-id' in request.session)
    if 'session-id' in request.session:
        company_data = get_company_data(request)
        print(company_data)
        response['companyName'] = company_data.get('name', '')
        response['companyType'] = company_data.get('companyType', {}).get('name', '')
        response['companyWeb'] = company_data.get('websiteUrl', '')
        specialties = ", ".join(company_data.get('specialties',{}).get('values',''))
        response['companySpecialty'] = specialties
        response['squareLogoUrl'] = company_data.get('squareLogoUrl', '')
        response['companyDescription'] = company_data.get('description', '')
        response['flag'] = True;
    else:
        response['flag'] = False;
        return redirect('/')
    return render(request, 'compProfile.html', response)

def get_company_id(request):
    token = request.session['session-id']
    url = "https://api.linkedin.com/v1/companies?oauth2_access_token="+token+"&format=json&is-company-admin=true"
    company_id = requests.request("GET", url=url)
    company_id = json.loads(company_id.content.decode('utf8'))
    print(company_id['values'])
    company_id = str(company_id['values'][-1]['id'])
    print(company_id)
    return company_id

def get_company_data(request):
    token = request.session['session-id']
    cpy_id = request.session['company_id']
    url = "https://api.linkedin.com/v1/companies/"+cpy_id+":(id,name,ticker,description,company-type,website-url,specialties,square-logo-url)?oauth2_access_token="+token+"&format=json"
    company_data = requests.request("GET", url=url)
    company_data = json.loads(company_data.content.decode('utf8'))
    return company_data

fitur2/templates/compProfile.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
Profile Perusahaan
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/fitur2.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/fitur1.css' %}" />
{% endblock %}

{% block header %}
{% include "partials/header.html" %}
{% endblock %}

{% block content %}
<section style="height: auto;">
  <!-- Banner -->
  <section id="banner" style="background-image: url('https://picsum.photos/1900/1080?image=1078')">
    <div class="inner">
      <header>
        <h1>Company Dashboard</h1>
        <p id="companyName">Welcome "{{companyName}}"</p>
      </header>
      <a href="{% url 'forum:index' %}" class="button big" style="background-color: black">Lihat Forum</a>
      <a href="#" class="button big" style="background-color: black">Cari Mahasiswa</a>
    </div>
  </section>

  <!-- Section -->
  <section class="wrapper style1">
    <div class="inner">
      <!-- 2 Columns -->
      <h2>About Company</h3>
      <div class="flex flex-1">
        <div class="col col1">
          <p id="about">{{companyDescription}}</p>
        </div>
        <div class="col col2">
          <h5 id="companyType">Company Type: {{companyType}}</h5>
          <h5 id="companyWeb">Website: {{companyWeb}}</h5>
          <h5 id="companySpecialty"><b>Specialities: {{companySpecialty}}</h5>
        </div>
      </div>
      <a href="#" class="button">Learn More</a>
    </div>
  </section>
  {% endblock %}

  {% block javascript %}
  {% endblock %}