fitur1/urls.py
from django.conf.urls import url
from .views import request_token, index, request_auth, auth_logout
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^authenticate/', request_auth, name='authenticate'),
    url(r'^request-token/', request_token , name='get_token'),
    url(r'^logout/', auth_logout , name='logout'),
]

fitur3/urls.py
from django.conf.urls import url
from .views import *
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', add, name='add'),
    url(r'^delete/(?P<id>\d)/$', delete_forum, name='delete_forum'),
]

tp2_uyay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import fitur1.urls as fitur1
import fitur2.urls as fitur2
import fitur3.urls as forum
import fitur4.urls as fitur4

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(fitur1, namespace='login')),
    url(r'^$', RedirectView.as_view(url='login/', permanent = True), name = '$'),
    url(r'^profile/', include(fitur2, namespace='fitur2')),
    url(r'^forum/', include(forum, namespace='forum')),
    url(r'^fitur4/', include(fitur4, namespace='fitur4')),
]

fitur3/models.py
from django.db import models
from fitur1.models import Company

# Create your models here.
class Forum(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    company = models.ForeignKey(Company)
    content = models.TextField(max_length=500)

    class Meta:
       ordering = ['id']

class Comment(models.Model):
    name    = models.CharField(max_length=140)
    from_company = models.BooleanField(default=False)
    #  title   = models.CharField(max_length=140)
    content = models.CharField(max_length=500)
    forum   = models.ForeignKey(Forum)
    created_on = models.DateTimeField(auto_now_add=True)

fitur3/forms.py
from django import forms

class ForumForm(forms.Form):
    content = forms.CharField(max_length=500)

fitur3/views.py
from django.shortcuts import render, redirect
from fitur1.models import Company
from .models import Forum, Comment
from .forms import ForumForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
response = {}
def index(request):
    if 'session-id' not in request.session or 'company_id' not in request.session:
        response['flag'] = False;
        return redirect('/')
    company = Company.objects.filter(companyID=request.session["company_id"]).first()
    forum_list = Forum.objects.all().filter(company=company)
    paginator = Paginator(forum_list, 3)

    page = request.GET.get('page')
    try:
        forum = paginator.page(page)
    except:
        forum = paginator.page(1)

    response['forum'] = forum
    response['flag'] = True;

    return render(request, 'forum.html', response)

def add(request):
    if 'session-id' not in request.session or 'company_id' not in request.session:
        return redirect('/')
    if request.method == 'POST':
        form = ForumForm(request.POST)
        response['form'] = form
        if form.is_valid():
            company = Company.objects.filter(companyID=request.session["company_id"]).first()
            Forum.objects.create(content=form.cleaned_data['content'], company=company)
            forum = Forum.objects.all()
            response['forum'] = forum
            return redirect('/forum/')
        else:
            forum = Forum.objects.all()
            response['forum'] = forum
            response['form'] = form
            return render(request, 'test.html', response)
    return redirect('/forum/')

def delete_forum(request, id):
    if 'session-id' not in request.session:
        return redirect('/')
    to_delete = Forum.objects.get(id=id)
    to_delete.delete()
    return redirect('/forum/')

fitur3/templates/forum.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block title %}
Forum Lowongan
{% endblock %}

{% block css %}
<script type="text/javascript" src="//platform.linkedin.com/in.js">
  api_key:   866hc1so0n9js9
  onLoad:    checkLoggedIn
  authorize: true
</script>
<!-- <link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" /> -->
<link rel="stylesheet" type="text/css" href="{% static 'css/fitur1.css' %}" />
{% endblock %}

{% block header %}
{% include "partials/header.html" %}
{% endblock %}

{% block content %}
<!-- Section -->
<section class="wrapper" style="background-image: url('https://picsum.photos/1900/1080?image=1031')">
  <div class="inner">
    <header class="align-center" >
      <h1>Create Job Posting</h1>
      <p style="color: black">Tell the world your company vacancies.</p>
      <!-- Form for new status -->
      <form class="card-text" method="POST" action="{% url 'forum:add' %}">
        {% csrf_token %}
        <div style="width: 75%; text-align:center; margin: 0 auto">
        <textarea placeholder="Describe your job requirements" class="form-control" name="content" rows="5" id="content" style="width: 100%" title="content"></textarea>
        </div>
        <button type="submit" class="btn btn-primary" style="margin: 10px 0 25px 0" id="button"> Submit </button>
      </form>
    </header>
  </div>
</section>

<!-- Section -->
<section class="wrapper">
  <!-- Print errors if any -->
  {% if form.errors %}
  {% for field in form %}
  {% for error in field.errors %}
  <div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
  </div>
  {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
  <div class="alert alert-danger">
    <strong>{{ error|escape }}</strong>
  </div>
  {% endfor %}
  {% endif %}

  <div class="inner">
      <div id="page" class="container">
          <div id="content">
            <div>
              {% for i in forum reversed %}
              <ul class="style1">
                <li class="first">
                  <h6 class="card-subtitle mb-2 text-muted"> {{ i.date }} </h6>
                  <p class="card-text"> {{ i.content }} </p>
                  <b><a href="/forum/delete/{{ i.id }}" class="button-style" id="">Delete</a></b>
                </li>
                <hr>
              </ul>
              {% endfor %}
            </div>
          </div>
      </div>
  </div>
  
  <nav>
    {% if forum.has_other_pages %}
    <ul class="pagination" style="justify-content: center; margin-top: 20px">
      {% if forum.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ forum.previous_page_number }}">&laquo;</a></li>
      {% else %}
      <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
      {% endif %}
      {% for i in forum.paginator.page_range %}
      {% if forum.number == i %}
      <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      {% if forum.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ forum.next_page_number }}">&raquo;</a></li>
      {% else %}
      <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
      {% endif %}
    </ul>
    {% endif %}
  </nav>
</section>
{% endblock %}

{% block javascript %}
<!-- <script src="{% static 'js/fitur3.js' %}"></script> -->
{% endblock %}